from __future__ import annotations

SHEET_NAME = "Plan1"

FIELD_TO_CELL = {
    "cpf_cnpj": "B5",
    "localizacao_1": "C6",
    "localizacao_2": "C7",
    "finalidade_vistoria": "C8",
    "comentario_localizacao": "A12",
    "imovel_nome": "A18",
    "area_total_ha": "D18",
    "area_pastagens_ha": "E18",
    "area_cultivo_ha": "F18",
    "area_financiada_bb_ha": "G18",
    "area_financiada_outros_ha": "H18",
    "atividade_principal": "I18",
    "principais_culturas": "K18",
    "benfeitorias_descricao": "A27",
    "benfeitorias_observacoes": "I27",
    "investimentos_comentarios": "D96",
    "insumos_comentarios": "D108",
    "recursos_proprios": "F126",
    "fornecedores_insumos": "F128",
    "fornecedores_praca": "I128",
    "observacoes_recursos": "D132",
    "perspectivas_comentarios": "B147",
    "outros_comentarios": "B184",
    "conclusao": "B193",
}

DATE_FIELDS = {
    "data_visita": ("J4", "Data da Visita:{}"),
    "data_assinatura": ("A195", "Data: {}"),
    "data_administracao": ("A204", "Data: {}"),
}

FIELD_ALIASES = {
    "cliente": "cliente",
    "nome": "nome",
    "nome_cliente": "cliente",
    "produtor": "cliente",
    "nome_produtor": "cliente",
    "mutuario": "cliente",
    "resumo_cliente": "resumo_cliente",
    "cabecalho_cliente": "resumo_cliente",
    "data": "data_visita",
    "data_visita": "data_visita",
    "data_da_visita": "data_visita",
    "data_assinatura": "data_assinatura",
    "cpf": "cpf_cnpj",
    "cnpj": "cpf_cnpj",
    "cpf_cnpj": "cpf_cnpj",
    "cnpj_cpf": "cpf_cnpj",
    "cidade": "cidade_uf",
    "cidade_uf": "cidade_uf",
    "municipio": "cidade_uf",
    "localizacao": "localizacao_1",
    "localizacao_1": "localizacao_1",
    "endereco": "localizacao_1",
    "endereco_localizacao": "localizacao_1",
    "endereco_localizacao_1": "localizacao_1",
    "localizacao_2": "localizacao_2",
    "endereco_2": "localizacao_2",
    "endereco_localizacao_2": "localizacao_2",
    "finalidade": "finalidade_vistoria",
    "finalidade_vistoria": "finalidade_vistoria",
    "comentario_localizacao": "comentario_localizacao",
    "localizacao_comentario": "comentario_localizacao",
    "vias_de_acesso": "comentario_localizacao",
    "acesso": "comentario_localizacao",
    "imovel": "imovel_nome",
    "imovel_nome": "imovel_nome",
    "nome_da_propriedade": "imovel_nome",
    "nome_das_propriedades": "imoveis",
    "nomes_das_propriedades": "imoveis",
    "propriedade": "imovel_nome",
    "propriedades": "imoveis",
    "fazenda": "imovel_nome",
    "fazendas": "imoveis",
    "imoveis": "imoveis",
    "imoveis_rurais": "imoveis",
    "tipo_de_exploracao": "tipo_exploracao",
    "area_total": "area_total_ha",
    "area_total_ha": "area_total_ha",
    "area_total_hectares": "area_total_ha",
    "area_de_pastagens_ha": "area_pastagens_ha",
    "area_de_cultivo_ha": "area_cultivo_ha",
    "area_alqueires": "area_alqueires",
    "area_pastagens": "area_pastagens_ha",
    "area_pastagens_ha": "area_pastagens_ha",
    "area_cultivo": "area_cultivo_ha",
    "area_cultivo_ha": "area_cultivo_ha",
    "area_financiada": "area_financiada_bb_ha",
    "area_financiada_bb": "area_financiada_bb_ha",
    "area_financiada_bb_ha": "area_financiada_bb_ha",
    "area_financiada_outros": "area_financiada_outros_ha",
    "area_financiada_outros_ha": "area_financiada_outros_ha",
    "atividade": "atividade_principal",
    "atividade_principal": "atividade_principal",
    "atividade_desenvolvida": "atividade_principal",
    "atividade_principal_desenvolvida": "atividade_principal",
    "atividades_desenvolvidas": "atividades_desenvolvidas",
    "situacao_produtiva": "situacao_produtiva",
    "culturas": "principais_culturas",
    "principais_culturas": "principais_culturas",
    "benfeitorias": "benfeitorias_descricao",
    "benfeitorias_descricao": "benfeitorias_descricao",
    "descricao_benfeitorias": "benfeitorias_descricao",
    "benfeitorias_conservacao": "benfeitorias_conservacao",
    "estado_benfeitorias": "benfeitorias_conservacao",
    "benfeitorias_observacoes": "benfeitorias_observacoes",
    "observacoes_benfeitorias": "benfeitorias_observacoes",
    "equipamentos": "equipamentos",
    "maquinas": "equipamentos",
    "maquinarios": "equipamentos",
    "maquinas_e_equipamentos": "equipamentos",
    "maquinarios_e_implementos": "equipamentos",
    "implementos": "equipamentos",
    "comentarios_investimentos": "investimentos_comentarios",
    "investimentos_comentarios": "investimentos_comentarios",
    "comentarios_insumos": "insumos_comentarios",
    "insumos_comentarios": "insumos_comentarios",
    "recursos_proprios": "recursos_proprios",
    "fornecedores_insumos": "fornecedores_insumos",
    "fornecedores_praca": "fornecedores_praca",
    "observacoes_recursos": "observacoes_recursos",
    "perspectivas_comentarios": "perspectivas_comentarios",
    "outros_comentarios": "outros_comentarios",
    "comentarios_finais": "outros_comentarios",
    "conclusao": "conclusao",
    "rebanho": "rebanho",
    "cabecas": "rebanho",
    "quantidade_animais": "rebanho",
    "fase": "fase",
    "ciclo": "fase",
    "futuros_projetos": "futuros_projetos",
    "projetos_futuros": "futuros_projetos",
    "raw_text": "raw_text",
}

INSUMO_ROWS = {
    "agua": 101,
    "energia_eletrica": 102,
    "estrutura_transporte": 103,
    "mao_de_obra": 104,
    "estrutura_armazenagem": 105,
    "pastagens": 106,
    "outros": 107,
}

PERSPECTIVA_ROWS = {
    "aquisicao_antecipada_de_insumos": 137,
    "aquisicao_de_animais": 138,
    "aquisicao_de_maquinas_e_equipamentos": 139,
    "construcao_reforma_ou_ampliacao_de_benfeitorias_e_instalacoes": 140,
    "correcao_de_solos": 141,
    "incremento_da_area_cultivada": 142,
    "implantacao_de_novas_culturas": 143,
    "implementacao_de_sistemas_de_armazenagem_irrigacao": 144,
    "reforma_de_pastagens": 145,
    "outros": 146,
}

EQUIPMENT_START_ROW = 51
EQUIPMENT_END_ROW = 76
EQUIPMENT_COLUMNS = {
    "descricao": "A",
    "fabricante": "E",
    "modelo": "F",
    "estado": "G",
    "financiado_bb": "I",
    "financiado_outros": "J",
    "segurado": "K",
    "gravame": "L",
    "outras_informacoes": "M",
}

PHOTO_SLOTS = [
    "D209",
    "D228",
    "D247",
    "D269",
    "D289",
    "D307",
    "D327",
    "D348",
    "D365",
    "C386",
    "D407",
    "D425",
    "D448",
    "D466",
    "D488",
    "D508",
    "C526",
    "D607",
    "C629",
    "D651",
    "D674",
    "D695",
    "D718",
    "D740",
    "D762",
    "D784",
    "C806",
    "D828",
    "C850",
    "D872",
    "D894",
    "C915",
    "D937",
    "D959",
    "D981",
    "D1003",
    "D1025",
    "D1047",
    "D1069",
]

PHOTO_ANCHORS = [
    (211, 3, 228, 10),
    (230, 3, 246, 10),
    (249, 3, 268, 10),
    (271, 3, 289, 10),
    (291, 3, 307, 9),
    (309, 3, 328, 10),
    (329, 3, 348, 10),
    (350, 3, 366, 10),
    (367, 3, 387, 10),
    (388, 3, 406, 10),
    (409, 3, 425, 10),
    (427, 3, 442, 10),
    (446, 3, 465, 10),
    (468, 3, 488, 10),
    (490, 3, 508, 10),
    (510, 3, 526, 10),
    (528, 2, 603, 9),
    (605, 2, 625, 10),
    (628, 3, 647, 9),
    (649, 3, 669, 10),
    (671, 3, 689, 10),
    (692, 3, 712, 9),
    (714, 3, 733, 10),
    (736, 3, 755, 10),
    (758, 3, 777, 10),
    (780, 3, 799, 10),
    (802, 3, 822, 10),
    (824, 3, 844, 10),
    (846, 3, 865, 9),
    (868, 3, 887, 10),
    (890, 3, 910, 10),
    (911, 3, 931, 10),
    (933, 3, 953, 10),
    (955, 3, 975, 10),
    (977, 3, 997, 10),
    (999, 3, 1019, 10),
    (1021, 3, 1041, 10),
    (1043, 3, 1063, 9),
    (1065, 3, 1085, 9),
]

PHOTO_MAX_SIZE = (520, 330)
