from __future__ import annotations

SHEET_NAME = "Plan1"

FIELD_TO_CELL = {
    "cpf_cnpj": "B5",
    "localizacao_1": "C6",
    "localizacao_2": "C7",
    "finalidade_vistoria": "C8",
    "comentario_localizacao": "A12",
    "imovel_nome": "A18",
    "area_total_ha": "D18",
    "area_pastagens_ha": "E18",
    "area_cultivo_ha": "F18",
    "area_financiada_bb_ha": "G18",
    "area_financiada_outros_ha": "H18",
    "atividade_principal": "I18",
    "principais_culturas": "K18",
    "benfeitorias_descricao": "A27",
    "benfeitorias_observacoes": "I27",
    "investimentos_comentarios": "D93",
    "insumos_comentarios": "D105",
    "recursos_proprios": "F123",
    "fornecedores_insumos": "F125",
    "fornecedores_praca": "I125",
    "observacoes_recursos": "D129",
    "perspectivas_comentarios": "B144",
    "outros_comentarios": "B181",
    "conclusao": "B190",
}

DATE_FIELDS = {
    "data_visita": ("J4", "Data da Visita:{}"),
    "data_assinatura": ("A195", "Data: {}"),
    "data_administracao": ("A204", "Data: {}"),
}

FIELD_ALIASES = {
    "cliente": "cliente",
    "nome": "nome",
    "nome_cliente": "cliente",
    "produtor": "cliente",
    "nome_produtor": "cliente",
    "mutuario": "cliente",
    "resumo_cliente": "resumo_cliente",
    "cabecalho_cliente": "resumo_cliente",
    "data": "data_visita",
    "data_visita": "data_visita",
    "data_da_visita": "data_visita",
    "data_assinatura": "data_assinatura",
    "cpf": "cpf_cnpj",
    "cnpj": "cpf_cnpj",
    "cpf_cnpj": "cpf_cnpj",
    "cnpj_cpf": "cpf_cnpj",
    "cidade": "cidade_uf",
    "cidade_uf": "cidade_uf",
    "municipio": "cidade_uf",
    "localizacao": "localizacao_1",
    "localizacao_1": "localizacao_1",
    "endereco": "localizacao_1",
    "endereco_localizacao": "localizacao_1",
    "endereco_localizacao_1": "localizacao_1",
    "localizacao_2": "localizacao_2",
    "endereco_2": "localizacao_2",
    "endereco_localizacao_2": "localizacao_2",
    "finalidade": "finalidade_vistoria",
    "finalidade_vistoria": "finalidade_vistoria",
    "comentario_localizacao": "comentario_localizacao",
    "localizacao_comentario": "comentario_localizacao",
    "vias_de_acesso": "comentario_localizacao",
    "acesso": "comentario_localizacao",
    "imovel": "imovel_nome",
    "imovel_nome": "imovel_nome",
    "nome_da_propriedade": "imovel_nome",
    "nome_das_propriedades": "imoveis",
    "nomes_das_propriedades": "imoveis",
    "propriedade": "imovel_nome",
    "propriedades": "imoveis",
    "fazenda": "imovel_nome",
    "fazendas": "imoveis",
    "imoveis": "imoveis",
    "imoveis_rurais": "imoveis",
    "tipo_de_exploracao": "tipo_exploracao",
    "area_total": "area_total_ha",
    "area_total_ha": "area_total_ha",
    "area_total_hectares": "area_total_ha",
    "area_de_pastagens_ha": "area_pastagens_ha",
    "area_de_cultivo_ha": "area_cultivo_ha",
    "area_alqueires": "area_alqueires",
    "area_pastagens": "area_pastagens_ha",
    "area_pastagens_ha": "area_pastagens_ha",
    "area_cultivo": "area_cultivo_ha",
    "area_cultivo_ha": "area_cultivo_ha",
    "area_financiada": "area_financiada_bb_ha",
    "area_financiada_bb": "area_financiada_bb_ha",
    "area_financiada_bb_ha": "area_financiada_bb_ha",
    "area_financiada_outros": "area_financiada_outros_ha",
    "area_financiada_outros_ha": "area_financiada_outros_ha",
    "atividade": "atividade_principal",
    "atividade_principal": "atividade_principal",
    "atividade_desenvolvida": "atividade_principal",
    "atividade_principal_desenvolvida": "atividade_principal",
    "atividades_desenvolvidas": "atividades_desenvolvidas",
    "situacao_produtiva": "situacao_produtiva",
    "culturas": "principais_culturas",
    "principais_culturas": "principais_culturas",
    "benfeitorias": "benfeitorias_descricao",
    "benfeitorias_descricao": "benfeitorias_descricao",
    "descricao_benfeitorias": "benfeitorias_descricao",
    "benfeitorias_conservacao": "benfeitorias_conservacao",
    "estado_benfeitorias": "benfeitorias_conservacao",
    "benfeitorias_observacoes": "benfeitorias_observacoes",
    "observacoes_benfeitorias": "benfeitorias_observacoes",
    "comentarios_investimentos": "investimentos_comentarios",
    "investimentos_comentarios": "investimentos_comentarios",
    "comentarios_insumos": "insumos_comentarios",
    "insumos_comentarios": "insumos_comentarios",
    "recursos_proprios": "recursos_proprios",
    "fornecedores_insumos": "fornecedores_insumos",
    "fornecedores_praca": "fornecedores_praca",
    "observacoes_recursos": "observacoes_recursos",
    "perspectivas_comentarios": "perspectivas_comentarios",
    "outros_comentarios": "outros_comentarios",
    "comentarios_finais": "outros_comentarios",
    "conclusao": "conclusao",
    "rebanho": "rebanho",
    "cabecas": "rebanho",
    "quantidade_animais": "rebanho",
    "fase": "fase",
    "ciclo": "fase",
    "futuros_projetos": "futuros_projetos",
    "projetos_futuros": "futuros_projetos",
    "raw_text": "raw_text",
}

INSUMO_ROWS = {
    "agua": 98,
    "energia_eletrica": 99,
    "estrutura_transporte": 100,
    "mao_de_obra": 101,
    "estrutura_armazenagem": 102,
    "pastagens": 103,
    "outros": 104,
}

PERSPECTIVA_ROWS = {
    "aquisicao_antecipada_de_insumos": 134,
    "aquisicao_de_animais": 135,
    "aquisicao_de_maquinas_e_equipamentos": 136,
    "construcao_reforma_ou_ampliacao_de_benfeitorias_e_instalacoes": 137,
    "correcao_de_solos": 138,
    "incremento_da_area_cultivada": 139,
    "implantacao_de_novas_culturas": 140,
    "implementacao_de_sistemas_de_armazenagem_irrigacao": 141,
    "reforma_de_pastagens": 142,
    "outros": 143,
}

EQUIPMENT_START_ROW = 51
EQUIPMENT_END_ROW = 76
EQUIPMENT_COLUMNS = {
    "descricao": "A",
    "fabricante": "E",
    "modelo": "F",
    "estado": "G",
    "financiado_bb": "I",
    "financiado_outros": "J",
    "segurado": "K",
    "gravame": "L",
    "outras_informacoes": "M",
}

PHOTO_SLOTS = [
    "D209",
    "D228",
    "D247",
    "D269",
    "D289",
    "D307",
    "D327",
    "D348",
    "D365",
    "C386",
    "D407",
    "D425",
    "D448",
    "D466",
    "D488",
    "D508",
    "C526",
    "D607",
    "C629",
    "D651",
    "D674",
    "D695",
    "D718",
    "D740",
    "D762",
    "D784",
    "C806",
    "D828",
    "C850",
    "D872",
    "D894",
    "C915",
    "D937",
    "D959",
    "D981",
    "D1003",
    "D1025",
    "D1047",
    "D1069",
]

PHOTO_ANCHORS = [
    (208, 3, 225, 9),
    (227, 3, 243, 9),
    (246, 3, 265, 10),
    (268, 3, 286, 10),
    (288, 3, 304, 9),
    (306, 3, 325, 10),
    (326, 3, 345, 9),
    (347, 3, 363, 10),
    (364, 3, 384, 10),
    (385, 2, 403, 10),
    (406, 3, 422, 9),
    (424, 3, 444, 9),
    (447, 3, 462, 10),
    (465, 3, 485, 10),
    (487, 3, 505, 9),
    (507, 3, 523, 10),
    (525, 2, 544, 9),
    (606, 3, 627, 9),
    (628, 2, 648, 9),
    (650, 3, 670, 10),
    (673, 3, 692, 9),
    (694, 3, 715, 9),
    (717, 3, 736, 9),
    (739, 3, 758, 9),
    (761, 3, 780, 9),
    (783, 3, 802, 9),
    (805, 2, 825, 10),
    (827, 3, 847, 9),
    (849, 2, 868, 9),
    (871, 3, 890, 10),
    (893, 3, 913, 9),
    (914, 2, 934, 9),
    (936, 3, 956, 9),
    (958, 3, 978, 9),
    (980, 3, 1000, 9),
    (1002, 3, 1022, 9),
    (1024, 3, 1044, 9),
    (1046, 3, 1066, 9),
    (1068, 3, 1088, 9),
]

PHOTO_MAX_SIZE = (520, 330)
